### ISSUE TITLE
Questions regarding to the paper itself

### ISSUE THREAD

**Issue by wylapp** [Jyonn/GENRE-requests#5]
Hello dear authors!
After intensive reading, I raised some questions. 

1. Figure 2 is quite confusing. First, if the similarity between "The Lion King" and "The Lions of Al-Rassan" is fixed as 1, then the denominator of $d_{i,j}$ is zero ($s_{blue, orange}=1$). This seems not make sense. Second, what do the dashed arrows between BERT and LLaMA, Glove and BERT mean?

2. The performance of baseline models are way lower than reported values in original papers. For example, MINER[1] is one of the strongest baseline models. These are the results reported in [1]:

|Model| AUC | MRR | nDCG@5 | nDCG@10|
|----|----|----|----|----|
|MINER w/ BERT-base| 69.61 | 33.97 | 37.62 | 43.90|
|MINER w/o BERT| 68.07 | 32.93 | - | 42.62|

However, these are the results reported in ONCE.

|Model| AUC | MRR | nDCG@5 | nDCG@10|
|----|----|----|----|----|
|MINER original| 63.88 | 32.19 | 33.04 | 39.45 |
|MINER w/ BERT12L| 65.82 | 32.77 | 34.02 | 40.19 |
| **ONCE** | 68.92 | 36.74 | 38.72 | 44.48|

I wonder, why MINER gets so much lower result (same issue also applies to NAML, NRMS, and FastFormer)? 
I would appreciate it if authors could answer these questions!

[1] https://aclanthology.org/2022.findings-acl.29.pdf

**Comment by Jyonn** [comment]
Hi, thanks for your attention!

1. By fixing the distance of <blue, orange>, we can see the trend of relative distance of <green, blue> and <green, orange> by applying difference language models, from GloVe, to BERT, and to LLaMA. For example, <blue, orange> is very close, compared with <blue, green> or <orange, green> when using GloVe embeddings.
2. There may have several reasons. Firstly, since MIND-small dataset only provide train and valid dataset, we preprocess it with our scripts for **fair comparison**. Secondly, we set the hidden size to 64 in the experiments which seems to be small. We also conducted experiments with hidden size as 64 after the paper is published, and found an improvement of the model performance. Hence, we did not update the results. You can reproduce our results using our codes.

Best,

Qijiong

**Comment by wylapp** [comment]
That sounds reasonable. Thanks for your answers!

**Comment by Jyonn** [comment]
Sorry. We also conducted experiments with hidden size as `64` -> We also conducted experiments with hidden size as `256`.
